homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.6319
  longitude: -79.3716
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 66
  # metric for Metric, imperial for Imperial
  unit_system: metric

  customize:
    light.dining_level_3_0:
        friendly_name: Dining Lights
    light.family_level_2_0:
        friendly_name: Family Lights

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#weather:
  #platform: openweathermap
  #api_key: !secret openweather_key

sensor:
    - platform: yr
    - platform: wunderground
      api_key: !secret wunderground_key
      monitored_conditions:
          - weather_1d_metric
          - weather_1n_metric
          - weather_2d_metric
          - weather_2n_metric
          - weather_3d_metric
          - weather_3n_metric
          - weather_4d_metric
          - weather_4n_metric
          - temp_high_record_c
          - temp_high_1d_c
          - temp_c
          - feelslike_c
          - temp_low_record_c
          - temp_low_1d_c
          - wind_kph
          - wind_1d_kph
          - precip_1d_mm
          - precip_1d
          - alerts

group:
    daily_forecast:
        name: Daily Forecast
        entities:
            - sensor.pws_weather_1d_metric
            - sensor.pws_weather_1n_metric
            - sensor.pws_weather_2d_metric
            - sensor.pws_weather_2n_metric
            - sensor.pws_weather_3d_metric
            - sensor.pws_weather_3n_metric
            - sensor.pws_weather_4d_metric
            - sensor.pws_weather_4n_metric

    weather_overview:
        name: Weather Overview
        entities:
            - sensor.pws_weather_1d_metric
            - sensor.pws_temp_high_record_c
            - sensor.pws_temp_high_1d_c
            - sensor.pws_temp_c
            - sensor.pws_feelslike_c
            - sensor.pws_temp_low_1d_c
            - sensor.pws_temp_low_record_c
            - sensor.pws_precip_1d
            - sensor.pws_precip_1d_mm
            - sensor.pws_wind_kph
            - sensor.pws_wind_1d_kph
            - sensor.pws_alerts

# Text to speech
tts:
  platform: google

# IFTTT
ifttt:
    key: PF3Ul6PB8nwCWc0cqez6u

# zwave
zwave:
    usb_path: /dev/ttyACM0

# ecobee
ecobee:
    api_key: !secret ecobee_key


# Automations
automation: !include automations.yaml
